import express from 'express';
const userRouter = express.Router();
import { createUser, getUserById, getUsers } from '../controllers/userController.js';
import { getUsersAdmin } from '../controllers/userController.js';
import { verifyToken } from '../middlewares/verifyToken.js';
userRouter.get('/users', verifyToken, getUsers);
userRouter.post('/add-user', verifyToken, createUser);
userRouter.get('/user/:id', verifyToken, getUserById);
userRouter.get('/users-admin', verifyToken, getUsersAdmin);
export default userRouter;